### ISSUE TITLE
possible performance improvement

### ISSUE THREAD

**Issue by MartinMalinda** [tvanc/lineclamp#13]
https://github.com/tvanc/lineclamp/blob/master/src/LineClamp.js#L262

at the moment the algorithm tries to cut one char after another until it can do its thing.
it's precise but it's heavy on the browser a bit, especially if the text is long and is expected to be longer than the expected amount of lines quite a bit

for 1000 char text that is likely to cut to 200, it does 800 measurements

what it could do instead (a divide and conquer solution)

1) receives a string with length 100
2) checks if 100 passes, if yes returns
3) if not tries 50
4a) if 50 passess, tries 75, if passes, tries 87, keeps going until the delta is > 1. When the delta is 1, returns
4b) if 50 does not pass, tries 25, then 12, then maybe  18 and so again until delta is 1.

This algorithm would radically reduce the amount of checks for long texts

**Comment by MartinMalinda** [comment]
> for 1000 char text that is likely to cut to 200, it does 800 measurements

hm no, this seems wrong. It seems like it's the other way around, it would smaller amount of checks, depending on the number of words. Still the divide and conquer approach could help.

**Comment by tvanc** [comment]
The implementation details are a little different than described but `hardClamp()` is indeed linear. A binary-search approach like that used in `softClamp()` is drastically faster.

I'm currently still getting one test failing so I'll need to work through that but this will be a significant improvement. This will take `hardClamp()` from a time complexity of _O(n)_ to _O(log n)_ where _n_ is the number of words (not characters, fyi).

Thanks for the suggestion!
